networks:
    net:
          driver: bridge

services:
    nginxV1:
        image: nginx:latest
        container_name: nginxV1
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/dvaporoga
            - ./nginx/localhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - dvaporoga
            - postgres_dvaporoga
        networks:
            - net

    postgres_dvaporoga:
        image: postgres:latest
        container_name: dvaporoga_db
        restart: unless-stopped
        tty: true
        ports:
            - "6012:5432"
        environment:
            POSTGRES_DB: dvaporoga_db
            POSTGRES_USER: anton
            POSTGRES_PASSWORD: mL1zN9bB8feV
        networks:
            - net

    dvaporoga:
        build:
            context: .
            dockerfile: Dockerfile.dvaporoga
        container_name: dvaporoga
        tty: true
        volumes:
            - .:/var/www/dvaporoga
            - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - net
