networks:
    net:
          driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/dvaporoga
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - dvaporoga
            - postgres_dvaporoga
        networks:
            - net

    postgres_dvaporoga:
        image: postgres:latest
        container_name: dvaporoga_db
        restart: unless-stopped
        tty: true
        ports:
            - "5961:5432"
        environment:
            - POSTGRES_DB:${DB_DATABASE}
            - POSTGRES_USER:${DB_USERNAME}
            - POSTGRES_PASSWORD:${DB_PASSWORD}
        networks:
            - net

    dvaporoga:
        build:
            context: .
            dockerfile: Dockerfile.dvaporoga
        container_name: dvaporoga
        tty: true
        volumes:
            - .:/var/www/dvaporoga
        networks:
            - net
